### ISSUE TITLE
npm install does not work.

### ISSUE THREAD

**Issue by chamilu** [francoischalifour/myfeeds#31]
Hi,
[node version:  v8.9.4 / npm version: v5.6.0]
simply cloned codebase and ran `npm install`. and I'm getting this error:

`
 myfeeds@0.1.0 postinstall D:\myfeeds
> npm install --prefix ./server && npm install --prefix ./client

> myfeeds@0.1.0 postinstall D:\myfeeds\server\node_modules\myfeeds> npm install --prefix ./server && npm install --prefix ./client

+ myfeeds@0.1.0
updated 1 package in 0.481s
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\path....2018-07-04T15_32_09_672Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1npm ERR! myfeeds@0.1.0 postinstall: `npm install --prefix ./server && npm install --prefix ./client`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myfeeds@0.1.0 postinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\path....debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myfeeds@0.1.0 postinstall: `npm install --prefix ./server && npm install --prefix ./client`
npm ERR! Exit status 1npm ERR!npm ERR! Failed at the myfeeds@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     C:\path....debug.log
`

**Comment by francoischalifour** [comment]
Hey, it seems like you're using a Windows machine.

You can run `npm install` in both `client/` and `server/` and it should do it!

**Comment by chamilu** [comment]
yes a pc. just wanted to run using a single command. Thanks anyway. 
👍
